name: cd

on:
  push:
    branches:
      - main
jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Context Information
        run: |
          echo "pr branch name: ${{ github.head_ref }}"
          echo "pr number: ${{ github.event.pull_request.number }}"
          echo "pr creator: ${{ github.event.pull_request.user.login }}"
      - uses: actions/checkout@v4
      - name: Auth for Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
