name: ci

on:
  pull_request:
    branches:
      - main
  push: # commitがPushされた場合に実行
  issue_comment:
    types: [created] # コメントが投稿された場合に実行
  schedule:
    - cron: "0 9 * * *" # 毎日hla 9:00 UTCに実行

jobs:
  build:
    # jobの実行環境
    runs-on: ubuntu-latest
    steps:
      # Pushされたコードのチェックアウト
      - uses: actions/checkout@v4
      # Go 1.22のセットアップ
      - name:  Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: フォーマット実行
        run: test -z $(gofmt -l .)
      - name: 静的解析実行
        run: go vet ./...
      - name: テスト実行
        run: go test
      # 詳細モードでgoのプログラムをビルド
      - name: Build
        run: go build -v .
