name: Go Test

on:
  push:

jobs:
  build:
    # jobの実行環境
    runs-on: ubuntu-latest
    steps:
      # Pushされたコードのチェックアウト
      - uses: actions/checkout@v4
      # Go 1.22のセットアップ
      - name:  Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      # 詳細モードでgoのプログラムをビルド
      - name: Build
        run: go build -v .
